spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:h2:tcp://localhost/~/auth
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
